from dataclasses import dataclass
from typing import List, Dict, Any, Optional
from datetime import datetime


@dataclass
class DocumentChunk:
    """
    A segment of text extracted from book content, with associated metadata
    (source URL, position in document, etc.)
    """
    chunk_id: str
    content: str
    source_url: str
    page_title: str
    chunk_order: int
    metadata: Dict[str, Any] = None

    def __post_init__(self):
        if self.metadata is None:
            self.metadata = {}


@dataclass
class EmbeddingVector:
    """
    A numerical representation of text content generated by Cohere models,
    used for similarity search
    """
    embedding_id: str
    chunk_id: str
    vector: List[float]
    model: str
    created_at: datetime = None

    def __post_init__(self):
        if self.created_at is None:
            self.created_at = datetime.utcnow()


@dataclass
class StorageRecord:
    """
    An entry in Qdrant Cloud containing an embedding vector and associated
    metadata for retrieval
    """
    record_id: str
    embedding_id: str
    payload: Dict[str, Any]
    vector_size: int